UPLOAD_FOLDER = 'static/img/SERVER_FILES/'
SQLALCHEMY_DATABASE_URI = 'mysql://root@127.0.0.1/agrostar'
SQLALCHEMY_TRACK_MODIFICATIONS = True
# WHOOSH_BASE = 'whoosh'
MAIL_USERNAME = 'agstarproject@gmail.com'
MAIL_PASSWORD = 'Dhruv2589'
MAIL_SERVER = 'smtp.googlemail.com'
MAIL_PORT = 587
MAIL_USE_TLS = True
WAY2SMS_APIKEY = '0HKTWPLVLEYYNE6LT411GDMUVOPFA65D'
WAY2SMS_SECRETKEY = 'HKL0LF69O5ZIHRE1'
PAYTM_MERCHANT_ID = 'uehZDw51552608286946'
PAYTM_API_KEY = 'YstL%hfsK4GI8eWJ'


